server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vol-service
          uri: lb://vol-service
          predicates:
            - Path=/vols/**
          # No rewrite needed - direct pass-through

        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotels/**
          filters:
            - RewritePath=/hotels/(?<segment>.*), /hotels/${segment}

        - id: booking-service-base
          uri: lb://booking-service
          predicates:
            - Path=/reservations
          # Handles POST /reservations
          
        - id: booking-service-search
          uri: lb://booking-service
          predicates:
            - Path=/reservations/**
          # Handles GET /reservations/search/... etc

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
